version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
      python: 3.11
    commands:
      - echo "Cloning public repo..."
      - git clone https://github.com/ASUCICREPO/Crohns-Colitis-Project.git .
      - echo "Installing dependencies..."
      
      # Install CDK
      - npm install -g aws-cdk@2.161.1
      
      # Install jq for JSON parsing
      - apt-get update && apt-get install -y jq
      
      - npm install -g @aws-amplify/cli
      
  pre_build:
    commands:
      - echo "Pre-build phase started on `date`"
      - cd Backend
      - npm install
      - npm run build
      
  build:
    commands:
      - echo "✅ Build started for Crohn's Colitis project"
      
      # Use timestamped stack name to avoid conflicts
      - export STACK_NAME="CrohnsColitisQBusinessStack-$(date +%s)"
      - echo "Using stack name: $STACK_NAME"
      
      # Bootstrap CDK if needed
      - echo "Bootstrapping CDK..."
      - cdk bootstrap --require-approval never
      
      # Deploy backend CDK stack
      - echo "Deploying backend infrastructure..."
      - cdk deploy --require-approval never --outputs-file ../outputs.json CrohnsColitisQBusinessStack
      
      # Extract API endpoints from CDK outputs
      - echo "Extracting API endpoints..."
      - cd ..
      - export CHAT_API_URL=$(cat outputs.json | jq -r '.CrohnsColitisQBusinessStack.ChatEndpoint')
      - export EMAIL_API_URL=$(cat outputs.json | jq -r '.CrohnsColitisQBusinessStack.EmailEndpoint')
      - export CONVERSATION_API_URL=$(cat outputs.json | jq -r '.CrohnsColitisQBusinessStack.ConversationEndpoint')
      - export TRANSLATE_API_URL=$(cat outputs.json | jq -r '.CrohnsColitisQBusinessStack.TranslateEndpoint')
      - export QBUSINESS_APP_ID=$(cat outputs.json | jq -r '.CrohnsColitisQBusinessStack.QBusinessApplicationId')
      
      # Configure frontend environment
      - echo "Configuring frontend with API endpoints..."
      - cd Frontend
      - echo "REACT_APP_CHAT_ENDPOINT=$CHAT_API_URL" > .env
      - echo "REACT_APP_EMAIL_ENDPOINT=$EMAIL_API_URL" >> .env
      - echo "REACT_APP_CONVERSATION_ENDPOINT=$CONVERSATION_API_URL" >> .env
      - echo "REACT_APP_APPLICATION_ID=$QBUSINESS_APP_ID" >> .env
      - echo "REACT_APP_REGION=us-west-2" >> .env
      
      # Install frontend dependencies and build
      - echo "Building frontend..."
      - npm install
      - npm run build
      
  post_build:
    commands:
      - echo "Post-build phase started on `date`"
      - echo "Frontend build completed. Amplify will handle deployment using amplify.yml"

artifacts:
  files:
    - outputs.json
    - Frontend/build/**/*
  name: crohns-colitis-deployment

cache:
  paths:
    - Backend/node_modules/**/*
    - Frontend/node_modules/**/*