version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
      python: 3.11
    commands:
      - echo "Cloning public repo..."
      - git clone https://github.com/ASUCICREPO/Crohns-Colitis-Project.git /tmp/repo
      - cp -r /tmp/repo/* .
      - echo "Installing AWS CDK CLI..."
      - npm install -g aws-cdk@2.161.1
      - cd Backend
      - npm install

  pre_build:
    commands:
      - npm run build
      - cdk bootstrap --require-approval never

  build:
    commands:
      - echo "=== PHASE 1 Backend Deployment ==="
      - echo "Deploying with SOURCE_EMAIL=$SOURCE_EMAIL and DESTINATION_EMAIL=$DESTINATION_EMAIL"
      - cdk deploy CrohnsColitisQBusinessStack --require-approval never --parameters sourceEmail=$SOURCE_EMAIL --parameters destinationEmail=$DESTINATION_EMAIL --outputs-file outputs.json
      - echo "=== Extracting API endpoints ==="
      - cat outputs.json
      - export API_URL=$(cat outputs.json | jq -r '.CrohnsColitisQBusinessStack.ApiEndpoint // empty')
      - export CHAT_API_URL=$(cat outputs.json | jq -r '.CrohnsColitisQBusinessStack.ChatEndpoint // empty')
      - export EMAIL_API_URL=$(cat outputs.json | jq -r '.CrohnsColitisQBusinessStack.EmailEndpoint // empty')
      - export CONVERSATION_API_URL=$(cat outputs.json | jq -r '.CrohnsColitisQBusinessStack.ConversationEndpoint // empty')
      - export QBUSINESS_APP_ID=$(cat outputs.json | jq -r '.CrohnsColitisQBusinessStack.QBusinessApplicationId // empty')
      - echo "Chat API URL $CHAT_API_URL"
      - echo "Email API URL $EMAIL_API_URL"

  post_build:
    commands:
      - echo "=== PHASE 2 Amplify App Setup ==="
      - AMPLIFY_APP_NAME="crohns-colitis-app"
      - AMPLIFY_BRANCH_NAME="main"
      - echo "Creating Amplify app with environment variables..."
      - aws amplify create-app --name "$AMPLIFY_APP_NAME" --repository "https://github.com/ASUCICREPO/Crohns-Colitis-Project" --platform WEB --environment-variables "REACT_APP_CHAT_ENDPOINT=$CHAT_API_URL,REACT_APP_EMAIL_ENDPOINT=$EMAIL_API_URL,REACT_APP_CONVERSATION_ENDPOINT=$CONVERSATION_API_URL,REACT_APP_APPLICATION_ID=$QBUSINESS_APP_ID,REACT_APP_REGION=us-west-2" > amplify-app.json || echo "App may already exist"
      - AMPLIFY_APP_ID=$(aws amplify list-apps --query "apps[?name=='$AMPLIFY_APP_NAME'].appId" --output text)
      - echo "Amplify App ID $AMPLIFY_APP_ID"
      - aws amplify create-branch --app-id "$AMPLIFY_APP_ID" --branch-name "$AMPLIFY_BRANCH_NAME" --environment-variables "REACT_APP_CHAT_ENDPOINT=$CHAT_API_URL,REACT_APP_EMAIL_ENDPOINT=$EMAIL_API_URL,REACT_APP_CONVERSATION_ENDPOINT=$CONVERSATION_API_URL,REACT_APP_APPLICATION_ID=$QBUSINESS_APP_ID,REACT_APP_REGION=us-west-2" || echo "Branch may already exist"
      - aws amplify start-build --app-id "$AMPLIFY_APP_ID" --branch-name "$AMPLIFY_BRANCH_NAME"
      - echo "=== Deployment Complete ==="
      - echo "Backend deployed successfully"
      - echo "Frontend Amplify URL https://$AMPLIFY_BRANCH_NAME.$AMPLIFY_APP_ID.amplifyapp.com"
      - echo "Chat API $CHAT_API_URL"
      - echo "Email API $EMAIL_API_URL"

artifacts:
  files:
    - outputs.json
    - amplify-app.json
  name: crohns-colitis-deployment